cc_binary (
    name = "ExampleServer",
    srcs = [ "hello_world.cpp" ],
    visibility = ["//visibility:public"],
    deps = [
        "//brick/server",
        "//brick/response",
        "//brick/request",
    ]
)