cc_library (
    name = "server",
    srcs = glob(["*.cc"]),
    hdrs =  glob ([ "*.hpp" ]),
    deps = [
        "//brick/request",
        "//brick/response",
        "//brick/utils/logging"
    ],
    visibility = ["//visibility:public"]
)